"""empty message

Revision ID: f0aadd242bd7
Revises: 
Create Date: 2020-05-26 20:22:45.536139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0aadd242bd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_data_email'), 'user_data', ['email'], unique=True)
    op.create_table('devices_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('eq_set_filename', sa.String(length=1000), nullable=True),
    sa.Column('device_info', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name')
    )
    op.create_index(op.f('ix_devices_data_device_info'), 'devices_data', ['device_info'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_data_device_info'), table_name='devices_data')
    op.drop_table('devices_data')
    op.drop_index(op.f('ix_user_data_email'), table_name='user_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
